### PR TITLE
[VRFPP-52] Import and export

### PR DESCRIPTION
**Pull request by lonesymmetry**
Add the ability to save workstations as JSON and open them again. The application writes out the transform position, orientation, and scale along with the substation type for each substation. On open, the application restores the state by instantiating each substation type and updating its transform to match the saved data. 

To test out this feature, use New, Save, Save As, and Open buttons under the file button in the toolbar.

### CODE REVIEW

**Comment by lonesymmetry** [comment]
I'm going to add missing comments before I mark this as ready for review

**Review by macovskym — CHANGES_REQUESTED** [review]
Looks great! My only request is that you grey out the "Save" button if the workstation hasn't been saved yet, as it seems to just cause an error in this case.

**Comment by lonesymmetry** [comment]
I actually do that in PR #32, which is when I re-addressed the UI associated with these import-export processes.

**Review by macovskym — APPROVED** [review]
Ok, I'll approve this PR and move my comment then.

**Pull request merged**
